apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls-cert-std
  namespace: integrated # Use the namespace where your applications reside
spec:
  secretName: myapp-tls-secret-std # The secret where the certificate and key will be stored
  issuerRef:
    name: letsencrypt-prod # Must match the ClusterIssuer name
    kind: ClusterIssuer
  commonName: provider-std-sovity.tvsdevops.co.uk # Primary subdomain (can be any one of your subdomains)
  dnsNames:
    - provider-std-sovity.tvsdevops.co.uk
    - consumer-std-sovity.tvsdevops.co.uk
