apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: consumer-connector-db-data
  name: consumer-connector-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
