apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: consumer-cp-db
  name: consumer-cp-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: consumer-cp-db 
