apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: consumer-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: consumer.local
      http:
        paths:
          - path: /api/management(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: consumer-connector
                port:
                  number: 11002
          - path: /api/dsp(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: consumer-connector
                port:
                  number: 11003
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: consumer-ui
                port:
                  number: 8080
