apiVersion: v1
data:
  nginx.provider.conf: |
    events {}

    http {
        upstream management_api {
            server provider-connector.master.svc.cluster.local:11002;
        }

        upstream dsp_api {
            server provider-connector.master.svc.cluster.local:11003;
        }

        upstream frontend {
            server provider-ui.master.svc.cluster.local:8080;
        }

        server {
            listen 80;

            location ~ ^/api/management($|/.*) {
                proxy_pass http://management_api;
            }

            location ~ ^/api/dsp($|/.*) {
                proxy_pass http://dsp_api;
            }

            location / {
                proxy_pass http://frontend;
            }
        }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: provider
  name: provider-cm0
