apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: provider-connector-db
  name: provider-connector-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: provider-connector-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: provider-connector-db
    spec:
      initContainers:
        - name: init-volume
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /mnt/data/provider-subdir-1 && chown -R 999:999 /mnt/data/provider-subdir-1
          volumeMounts:
            - name: provider-connector-db-data
              mountPath: /mnt/data
      containers:
        - env:
            - name: POSTGRES_DB
              value: db-name
            - name: POSTGRES_PASSWORD
              value: db-pass
            - name: POSTGRES_USER
              value: db-user
          image: docker.io/postgres:16-alpine
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "db-user"
                - "--dbname=db-name"
            failureThreshold: 10
            periodSeconds: 1
            timeoutSeconds: 5
          name: provider-connector-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: provider-connector-db-data
              subPath: provider-subdir-1
      restartPolicy: Always
      volumes:
        - name: provider-connector-db-data
          persistentVolumeClaim:
            claimName: provider-connector-db-data
